/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2so;

/**
 *
 * @author luismanzano
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nivel1_1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nivel2_1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nivel3_1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RobotText = new javax.swing.JLabel();
        Nivel1_2 = new javax.swing.JLabel();
        Nivel1_3 = new javax.swing.JLabel();
        Nivel1_4 = new javax.swing.JLabel();
        Nivel1_5 = new javax.swing.JLabel();
        Nivel1_6 = new javax.swing.JLabel();
        Nivel2_2 = new javax.swing.JLabel();
        Nivel2_3 = new javax.swing.JLabel();
        Nivel2_4 = new javax.swing.JLabel();
        Nivel2_5 = new javax.swing.JLabel();
        Nivel2_6 = new javax.swing.JLabel();
        Nivel3_2 = new javax.swing.JLabel();
        Nivel3_3 = new javax.swing.JLabel();
        Nivel3_4 = new javax.swing.JLabel();
        Nivel3_5 = new javax.swing.JLabel();
        Nivel3_6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mantenimiento_1 = new javax.swing.JLabel();
        Mantenimiento_2 = new javax.swing.JLabel();
        Mantenimiento_3 = new javax.swing.JLabel();
        Mantenimiento_4 = new javax.swing.JLabel();
        Mantenimiento_5 = new javax.swing.JLabel();
        Mantenimiento_6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nivel 1");

        Nivel1_1.setText("jLabel2");

        jLabel3.setText("Nivel 2");

        Nivel2_1.setText("jLabel4");

        jLabel5.setText("Nivel 3");

        Nivel3_1.setText("jLabel6");

        jLabel7.setText("Robot");

        RobotText.setText("jLabel8");

        Nivel1_2.setText("jLabel2");

        Nivel1_3.setText("jLabel4");

        Nivel1_4.setText("jLabel6");

        Nivel1_5.setText("jLabel8");

        Nivel1_6.setText("jLabel9");

        Nivel2_2.setText("jLabel10");

        Nivel2_3.setText("jLabel11");

        Nivel2_4.setText("jLabel12");

        Nivel2_5.setText("jLabel13");

        Nivel2_6.setText("jLabel14");

        Nivel3_2.setText("jLabel15");

        Nivel3_3.setText("jLabel16");

        Nivel3_4.setText("jLabel17");

        Nivel3_5.setText("jLabel18");

        Nivel3_6.setText("jLabel19");

        jLabel2.setText("Mantenimiento");

        Mantenimiento_1.setText("jLabel4");

        Mantenimiento_2.setText("jLabel6");

        Mantenimiento_3.setText("jLabel8");

        Mantenimiento_4.setText("jLabel9");

        Mantenimiento_5.setText("jLabel10");

        Mantenimiento_6.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(294, 294, 294))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Nivel1_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nivel1_5)
                                .addGap(18, 18, 18)
                                .addComponent(Nivel1_4)
                                .addGap(18, 18, 18)
                                .addComponent(Nivel1_3)
                                .addGap(18, 18, 18)
                                .addComponent(Nivel1_2)
                                .addGap(18, 18, 18)
                                .addComponent(Nivel1_1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Mantenimiento_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mantenimiento_5)
                                .addGap(18, 18, 18)
                                .addComponent(Mantenimiento_4)
                                .addGap(18, 18, 18)
                                .addComponent(Mantenimiento_3)
                                .addGap(18, 18, 18)
                                .addComponent(Mantenimiento_2)
                                .addGap(18, 18, 18)
                                .addComponent(Mantenimiento_1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(Nivel3_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(Nivel3_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nivel3_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nivel3_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nivel3_2)
                                .addGap(18, 18, 18)
                                .addComponent(Nivel3_1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Nivel2_6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Nivel2_5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Nivel2_4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Nivel2_3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Nivel2_2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Nivel2_1))
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(320, 320, 320)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46))
                            .addComponent(RobotText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nivel1_1)
                    .addComponent(Nivel1_2)
                    .addComponent(Nivel1_3)
                    .addComponent(Nivel1_4)
                    .addComponent(Nivel1_5)
                    .addComponent(Nivel1_6))
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RobotText)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nivel3_1)
                            .addComponent(Nivel3_2)
                            .addComponent(Nivel3_3)
                            .addComponent(Nivel3_4)
                            .addComponent(Nivel3_5)
                            .addComponent(Nivel3_6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nivel2_1)
                            .addComponent(Nivel2_2)
                            .addComponent(Nivel2_3)
                            .addComponent(Nivel2_4)
                            .addComponent(Nivel2_5)
                            .addComponent(Nivel2_6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mantenimiento_1)
                    .addComponent(Mantenimiento_2)
                    .addComponent(Mantenimiento_3)
                    .addComponent(Mantenimiento_4)
                    .addComponent(Mantenimiento_5)
                    .addComponent(Mantenimiento_6))
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                Administrador administrador = new Administrador();
                administrador.programa();
            }
        });
    }
    
        
    public static void setNivel1(String string){
        Nivel1_1.setText(string);
    }
    
    public static void setNivel2(String string){
        Nivel2_1.setText(string);
    }
    
    public static void setNivel3(String string){
        Nivel3_1.setText(string);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Mantenimiento_1;
    public static javax.swing.JLabel Mantenimiento_2;
    public static javax.swing.JLabel Mantenimiento_3;
    public static javax.swing.JLabel Mantenimiento_4;
    public static javax.swing.JLabel Mantenimiento_5;
    public static javax.swing.JLabel Mantenimiento_6;
    public static javax.swing.JLabel Nivel1_1;
    public static javax.swing.JLabel Nivel1_2;
    public static javax.swing.JLabel Nivel1_3;
    public static javax.swing.JLabel Nivel1_4;
    public static javax.swing.JLabel Nivel1_5;
    public static javax.swing.JLabel Nivel1_6;
    public static javax.swing.JLabel Nivel2_1;
    public static javax.swing.JLabel Nivel2_2;
    public static javax.swing.JLabel Nivel2_3;
    public static javax.swing.JLabel Nivel2_4;
    public static javax.swing.JLabel Nivel2_5;
    public static javax.swing.JLabel Nivel2_6;
    public static javax.swing.JLabel Nivel3_1;
    public static javax.swing.JLabel Nivel3_2;
    public static javax.swing.JLabel Nivel3_3;
    public static javax.swing.JLabel Nivel3_4;
    public static javax.swing.JLabel Nivel3_5;
    public static javax.swing.JLabel Nivel3_6;
    public static javax.swing.JLabel RobotText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
